#!/bin/bash

shopt -s dotglob

#Укажите в кавычках имя скрипта
namescript="Копирование файлов в корень системы (Требуются root права)"

#Версия скрипта
let scriptversion=1

#Разместите ниже код вашего скрипта

echo "Имя хоста"
hostname
echo ""

function copy_files_in_root {
  if [[ -f "$dirfiles/scriptfiles-root.tar.gz" ]]; then
    echo -e "\nРаспаковка архива\n"
    (tar xpvfz "$dirfiles/scriptfiles-root.tar.gz" -C /) && echo -e "\nЗавершено\n" || echo -e "\nНе удалось распаковать\n"

  else
    echo -e "\nНе обнаружен файл scriptfiles-root.tar.gz\n"
    return 1
  fi
}

if [[ "$(id -u)" -eq 0 ]]; then
  copy_files_in_root
else
  echo -e "\nТребуются права root для выполнения скрипта\n"
  exit 1
fi

#Конец кода вашего скрипта
