#Файл script.conf используется для указания переменных, из файла скрипта sendcommand, которые вы хотите иметь возможность менять в копии скрипта при отправке (т.е. нет необходимости менять значения в эталонном файле скрипта вручную).

#При подготовке файлов к отправке, если файл script.conf есть в каталоге с отправляемым скриптом, будет задан вопрос, хотите ли вы внести изменения в переменные копии файла отправляемого скрипта (вопрос можно отключить через параметр skipchangescriptfile в sssc.conf).

#Вопросы задаются в порядке расположения секций в файле. Учитывайте это при использовании block_changes_values и terms_block_changes_curent_variable

#Формат заполнения
#[имя-переменной]
#typevalue=тип-переменной
#descvalue=Описание
#listvalue=значение1;значение2
#block_changes_values=значение-текущей-переменной1:имя-блокируемой-переменной1;имя-блокируемой-переменной2|значение-текущей-переменной2:имя-блокируемой-переменной1;имя-блокируемой-переменной2
#terms_block_changes_curent_variable=проверяемое-значение1:имя-проверяемой-переменной1;имя-проверяемой-переменной2|проверяемое-значение2:имя-проверяемой-переменной1;имя-проверяемой-переменной2

#Поле listvalue обязательно, если выбран тип переменной list

#terms_block_changes_curent_variable - необязательное поле, позволяющее указать условия, при которых вопрос не будет задан для текущей переменной. В проверяемом значении также можно указать not_null для проверки текстового поля, что оно не пустое.

#block_changes_values - необязательное поле, которое позволяет указать, для каких переменных не задавать вопрос об изменении, если значение текущей переменной соответствует указанному значению/условию. В значении текущей переменной также можно указать not_null для проверки текстового поля, что оно не пустое.

#Допускается использовать следующие типы переменной:
#number - любое число
#text - текстовое поле
#list - выбор из заданного списка значений
#massive - при выборе данного типа будет запрос значений для массива
#truefalse - выбор из значений 0/1

[forceinstall]
typevalue=truefalse
descvalue=Принудительная установка, даже если версия совпадает (1 - установить, 0 - пропустить)
