#!/bin/bash

#Укажите в кавычках имя скрипта
namescript="Наложение доменных групп на локальные через sss_override (Требуются root права)"

check_group_name='^[A-Za-zА-Яа-я0-9@._-]+$'
check_num='^[0-9]+$'

#Версия скрипта
let scriptversion=1

#Разместите ниже код вашего скрипта

#Список групп: 'доменная группа|локальная группа|признак-типа-группы|gid-группы'
#Признак-типа-группы - необязательное числовое значение, определяющее тип группы в случае создания (0 - обычная, 1 системная. По умолчанию 0, если не задано)
#gid-группы - необязательное числовое значение, определяющее gid группы в случае создания (Если не задано, то присвоится командой создания)
# Пример: list_name_group=('domain users|users|1|' 'astra-admin|astra-admin|1|' 'astra-console|astra-console|1|' 'audio|audio|1|' 'cdrom|cdrom|1|' 'dialout|dialout|1|' 'dip|dip|1|' 'floppy|floppy|1|' 'lpadmin|lpadmin|1|' 'netdev|netdev|1|' 'plugdev|plugdev|1|' 'scanner|scanner|1|' 'video|video|1|' 'linuxwine|linuxwine|0|1500')
list_name_group=()

#Создать локальную группу, если она отсутствует в системе
let create_local_group=0

#Имя домена. Если оставить пустым, то вычислиться командой hostname -d
domain_name=

#Файл конфигурации SSSD
conf_sssd="/etc/sssd/sssd.conf"

echo -e "\nВыполнение скрипта: $namescript"

#Если sss_override найден, то продолжается выполнение
if [[ -n "$(which sss_override 2>/dev/null)" ]]; then

  function domaingroup_in_local {
    if [[ "${#list_name_group[@]}" -gt "0" ]]; then

      #Если domain_name пуст, то вычисляем значение на основе имени хоста
      if [[ -z "$domain_name" ]]; then
        domain_name="$(hostname -d)"
      fi

      #Если domain_name не пуст, то продолжаем выполнение
      if [[ -n "$domain_name" ]]; then
        #Определение есть ли в файле конфигурации SSSD секция домена
        section_use_domain="$(cat "$conf_sssd" | grep '^\[.*\]$' | awk -F'[][]' '{print $2}' | grep -i "domain/$domain_name" | sed 's/\//\\\//g')"

        #Если секция найдена, то продолжается выполнение
        if [[ -n "$section_use_domain" ]]; then
          echo -e "\nСекция домена в файле конфинурации найдена"

          domain_name="$(echo "$section_use_domain" | cut -d '/' -f 2)"

          echo -e "\nПК подключен к домену $domain_name"

          #Определение имени следующей за section_use_domain секции. Если section_use_domain это последняя секция, то поиск в следующей команде будет произведен до конца файла, иначе будет действовать диапозон поиска в рамках одной секции
          nextsection="$(cat "$conf_sssd" | grep '^\[.*\]$' | awk -F'[][]' '{print $2}' | sed -n "/$section_use_domain/,+1 p" | tail -1 | sed 's/\//\\\//g')"

          #Ищем значение параметра use_fully_qualified_names в файле конфигурации
          status_use_full_name="$(sed -nr "/^\[$section_use_domain\]/,/^\[$nextsection\]/p" "$conf_sssd" | sed -nr "{ :l /^use_fully_qualified_names[ ]*=/ { s/[^=]*=[ ]*//; p; q;}; n; b l;}" | tr -d '\n')"

          #Формирование команды выполнения. Если полные имена включены, то к доменным группам будет добавлено имя домена в название.
          if [[ -n "$(echo "$status_use_full_name" | grep -i 'True')" ]]; then
            echo -e "\nВ файле конфигурации $conf_sssd включено использование полного доменного имени"

            runcmd='sss_override group-add "${list_name_group2[0]}@$domain_name" -n "${list_name_group2[1]}" -g "$(cat "/etc/group" | grep -w "^${list_name_group2[1]}" | cut -d ":" -f 3)"'
          else
            echo "В файле конфигурации $conf_sssd не включено использование полного доменного имени"

            runcmd='sss_override group-add "${list_name_group2[0]}" -n "${list_name_group2[1]}" -g "$(cat "/etc/group" | grep -w "^${list_name_group2[1]}" | cut -d ":" -f 3)"'
          fi

          #Перебор в цикле массива list_name_group
          for ((m = 0; m < ${#list_name_group[@]}; m++)); do

            #Если не пусто, то продолжается выполнение
            if [[ -n "${list_name_group[$m]}" ]]; then
              #Формируем новый массив в котором должно быть 2 значения
              readarray -d '|' -t list_name_group2 < <(echo "${list_name_group[$m]}" | tr -d '\n')

              #Если первое и второе значение массива list_name_group2 соответствуют условию проверки, то продолжается выполнение
              if [[ "${list_name_group2[0]}" =~ $check_group_name ]] && [[ "${list_name_group2[1]}" =~ $check_group_name ]]; then

                #Если группа найдена в системе, то запускается выполнение команды, иначе сначала будет попытка создать группу, если create_local_group равен 1
                if [[ "$(cat "/etc/group" | cut -d ':' -f 1 | grep -w "^${list_name_group2[1]}$" | wc -l)" -eq "1" ]]; then
                  echo -e "\nНастройка доменной группы ${list_name_group2[0]}"
                  eval "$runcmd"
                else
                  echo -e "\nЛокальная группа ${list_name_group2[1]} не найдена."

                  if [[ "$create_local_group" -eq "1" ]]; then

                    echo -e "\nВыполняется создание локальной группы и настройка доменной группы ${list_name_group2[0]}."
                    groupadd $([[ "${list_name_group2[2]}" =~ $check_num ]] && [[ "${list_name_group2[2]}" -eq "1" ]] && echo "-r ")$([[ "${list_name_group2[3]}" =~ $check_num ]] && echo "-g ${list_name_group2[3]} ")"${list_name_group2[1]}" && eval "$runcmd"
                  fi
                fi
              fi
            fi
          done
        else
          echo -e "\nНе найдена секция домена в конфигурации sssd"
          return 1
        fi
      else
        echo -e "\nПК не подключен к домену"
        return 1
      fi
    else
      echo -e "\nМассив list_name_group пуст"
      return 1
    fi
  }

  #Если скрипт запущен не от root, то выдаст ошибку
  if [[ "$(id -u)" -eq "0" ]]; then
    domaingroup_in_local
  else
    echo -e "\nТребуются права root для выполнения скрипта\n"
    exit 1
  fi
else
  echo -e "\nsss_override не обнаружен\n"
  exit 1
fi
